FROM node:23.4.0-alpine3.20

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install
# Can you add a script to the global package.json that does this?
RUN npm run db:generate
# Can you filter the build down to just one app?
RUN npm run user-app-build

CMD ["npm", "run", "start-user-app"]